implement EWKZ splitting
KIT-CMS/CombineHarvester pull request #1
Opened 2018-10-12 12:29 UTC by stwunsch

@janekbechtel @swozniewski passt das so?

2018-10-12 12:29 UTC, stwunsch commented
Siehe https://github.com/KIT-CMS/sm-htt-analysis/pull/22

2018-10-15 12:05 UTC, stwunsch commented
@janekbechtel sind die prozesse richtig zugeordnet?

2018-10-15 19:28 UTC, janekbechtel requested changes
1) https://github.com/KIT-CMS/CombineHarvester/blob/1993a4421edbdbc8e2fd6738cabb51ca724f3409/HTTSM2017/src/HttSystematics_SMRun2.cc#L166-L175
EWKJ fehlt und ZL sollte nicht dabei sein, oder?

2) https://github.com/KIT-CMS/CombineHarvester/blob/1993a4421edbdbc8e2fd6738cabb51ca724f3409/HTTSM2017/src/HttSystematics_SMRun2.cc#L382-L402
EWKL fehlt

3) https://github.com/KIT-CMS/CombineHarvester/blob/1993a4421edbdbc8e2fd6738cabb51ca724f3409/HTTSM2017/src/HttSystematics_SMRun2.cc#L214-L228

VVL ist das "gleiche" wie TTL, d.h. vor allem ein echtes tau und ein promptes muon oder elektron -> sollte parallel wie TTL behandelt werden und auch tau ES uncertainty applied bekommen

4) https://github.com/KIT-CMS/CombineHarvester/blob/1993a4421edbdbc8e2fd6738cabb51ca724f3409/HTTSM2017/src/HttSystematics_SMRun2.cc#L412-L415

EWKJ fehlt

2018-10-16 07:34 UTC, stwunsch commented
@janekbechtel Passt es jetzt so? Vielen Dank fuer das Review :)

2018-10-16 07:55 UTC, janekbechtel approved these changes

2018-10-16 07:55 UTC, janekbechtel commented
Sieht gut aus :)

2018-10-16 07:56 UTC, merged

2018-10-16 07:56 UTC, stwunsch commented
wunderbar!